spring:
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
  datasource:
    platform: mysql
    url: ${DATABASE_URL:jdbc:mysql://192.168.99.100:3306/christimas}
    username: ${DATABASE_USER:christimas}
    password: ${DATABASE_PASSWORD:123456}
  database:
    driverClassName: com.mysql.jdbc.Driver
  mail:
    host: ${SMTP_ADDRESS:smtp.gmail.com}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
  ldap:
    urls: ${LADAP_URLS}
    base: ${LDAP_BASE}
    username: ${LDAP_USERNAME}
    password: ${LDAP_PASSWORD}

server:
  port: 8080

azure:
  activedirectory:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    ActiveDirectoryGroups: ${GROUPS}